name: Build Windows exe

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Recombine 7z volumes into single archive
      shell: cmd
      run: copy /b assets.7z.* assets.7z

    - name: Unzip assets (Poppler & Tesseract)
      shell: cmd
      run: 7z x assets.7z -o.

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pymupdf paddleocr paddlepaddle opencv-python numpy pandas

    - name: Build standalone exe
      shell: cmd
      run: |
        pyinstaller --clean --onefile --noconsole --name ExtratorFaturas ^
          --additional-hooks-dir hooks ^
          --add-data "poppler-24.08.0;poppler-24.08.0" ^
          --add-data "Tesseract\\tesseract.exe;." ^
          --add-data "Tesseract\\tessdata;tessdata" ^
          --hidden-import paddle ^
          main_processor.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ExtratorFaturas.exe
        path: dist/ExtratorFaturas.exe
