name: Build Windows exe

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Recombine 7z volumes into single archive
      shell: cmd
      run: copy /b poppler.7z.* poppler.7z

    - name: Unzip assets (Poppler)
      shell: cmd
      run: 7z x poppler.7z -o.

    - name: Recombine PaddleOCR models
      shell: cmd
      run: copy /b paddle_models.7z.* paddle_models.7z
    
    - name: Unzip PaddleOCR models
      shell: cmd
      run: 7z x paddle_models.7z -opaddle_models


    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cx-Freeze pyinstaller pymupdf paddleocr paddlepaddle opencv-python numpy pandas openpyxl

    - name: Build standalone exe
      shell: cmd
      run: |
        pyinstaller --clean --onefile --name ExtratorFaturas ^
          --additional-hooks-dir hooks ^
          --hidden-import paddle ^
          --collect-all paddleocr ^
          --collect-all paddle ^
          --collect-all ppocr ^
          --collect-all ppstructure ^
          --add-data "poppler-24.08.0;poppler-24.08.0" ^
          --add-data "paddle_models;paddle_models" ^
          main_processor.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ExtratorFaturas.exe
        path: dist/ExtratorFaturas.exe
